project:
  type: website
  output-dir: "docs"
      
website:
  back-to-top-navigation: true
  reader-mode: false
  cookie-consent: false
  open-graph: true
  title: "Jeffrey Lin"
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jeffreylin24/
      - icon: twitter-x
        href: https://x.com/J_LinEPI/
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/epijlin/jeffrey-website/
          - text: Report a Bug
            href:  https://bugs.com/
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Work"
        href: work.qmd
      - text: "Life"
        href: life.qmd
  page-footer: 
    left: "&copy; Copyright 2024, Jeffrey Lin<br>Coming Soon"
    right: "Built with [Coming soon...](<link file>)"
    background: light
  search: 
    location: navbar
    type: overlay

format:
  html:
    include-in-header: header_announcement.html
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false

editor: visual

